[default]
workshop = [
    "3499977893", # ADT
    "1751569185", # Pythia
    "1923321700", # O&T Expansion Eden
    "463939057", # ace
    "450814997", # CBA
    "2020940806", # KAM
    "623475643" # 3DEN Enhanced
]

[eden]
extends = "default"
mission = "addons\\missions\\AFL_FiringRange.Stratis"

[pbo]
extends = "default"
file_patching = false
binarize = true
rapify = true
